### ISSUE TITLE
Website additions

### ISSUE THREAD

**Issue by 128-95** [kittycash/kittycash.com#17]
- [x] Create a short description that can replace the section "What is Kitty Cash on front page"

- [ ] Add to the What is Kitty Cash section the following segment:
 "We are: --> creating a Tamagotchi like game that lets you breed and trade Kitties 
                -->  building a platform for gaming on blockchain 
                -->  demonstrating the revolutionary potential of Skycoin technology" (the --> are              representing dots or maybe numbers, whatever looks better)
- [ ] add the download section at the bottom of the page. People can download our stickers there if they submit an email address.

**Comment by jdknives** [comment]
- [ ] Change the URL logo from the old to the new one

**Comment by jdknives** [comment]
- [ ] Add the new medium article to the blog. For some reason it is not showing up.

**Comment by bradkendall** [comment]
Is this still active?  Did you want me to add the downloads & what is KittyCash sections?

**Comment by jdknives** [comment]
@bradkendall I will think about the Skycoin explanation. probably an overkill at this point.

**Comment by jdknives** [comment]
@bradkendall also please add the branding guide

**Comment by jdknives** [comment]
updated it.
