### ISSUE TITLE
API scoreboard

### ISSUE THREAD

**Issue by jdknives** [kittycash/kittycash.com#33]
- [x] create an API for a scoreboard for the website game

- [x] assign responsibility for this task to someone (not Evan)

**Comment by jdknives** [comment]
@briancaine that one is done is it?

**Comment by briancaine** [comment]
Then we're done? Anything needed for deployment?

**Comment by bradkendall** [comment]
We need to host the scoreboard api and update the endpoints.

**Comment by 128-95** [comment]
- [ ] Deploy on own infrastructure [#4](https://github.com/kittycash/kitty-api/issues/4)

**Comment by briancaine** [comment]
So the scoreboard-api is deployed on staging. I'll be sure to bring it along as I develop the infrastructure.

Is there anything else we're missing for this ticket?
