### ISSUE TITLE
Update addresses of Legendary kitties

### ISSUE THREAD

**Issue by 128-95** [kittycash/kittycash.com#60]
Addresses to which the legendaries are actually send out:

|Pre-made Legendary|Address|
|---|---|
Magician | 2V4WJSE2YBKy7hs6eBirRCFQ6nXDvH9EJH6
Synth | rq7ZmPhKSx2GSqdJGsSSAyfh8mH2hjqBRM
Thor | SjmEfoYJ3htpnt3ZjLbodDpT2Mn2JM92mr
Apollo (dragon) | rkWWXVTML8pQ597SA3YtpeaccNUykjLPpd

|Customs |  Address |
|---|---|
Jackson | 594mF4kKWj5C2tcmQa1PAqH9YKMMCvrsS1
Steve Jobs | 2PREV3fvq3ehDwwx1nU14zoAZZhyyQ6EuPr
J.J. Jenkins | jptwiZAAAx5N7d5PY3f8QHF6wMmqiw1YCM
Audrey | sZpKYF24nsy3DfS8EsDvJEf3mXHxoiXb2S
Smurfette | 3baZkVdCkdghL6BkVr9Q6sTdTDGt3gQU3L
Hacker | 2ZRZQ9PAfhL9ziJjxyR9tUWWjHP77AW6gzv
Robot | Vi3q9bHZ7jRoEe8WTwzfeFkwq5YkDY9qXt

If a legendary is not mentioned, the owner did not request us to change the address.

**Comment by jdknives** [comment]
@bradkendall is that done?

**Comment by bradkendall** [comment]
No, I will get to this today.  I must have missed this.
