### ISSUE TITLE
Website changes

### ISSUE THREAD

**Issue by jdknives** [kittycash/kittycash.com#62]
- [ ] add submit question bar for faq (use join newsletter design)

- [x] change hacker cat to hardware cat (name) and description to "Developing Skycoin hardware". 

- [ ] think about Chinese font problem (apparently we use a google font that can't be displayed in china)

- [x] put hacker cat into custom section and add the new robo cat to custom section as well

- [ ] please fix this, it is the FAQ page
<img width="1085" alt="bildschirmfoto 2018-06-22 um 11 54 06" src="https://user-images.githubusercontent.com/36450093/41780488-1f51719c-7635-11e8-9c38-7c3206ce017f.png">

- [ ] please remove white, and use the legendary pictures without the sold sign in the middle since we now have the new sold sign on the top left
<img width="306" alt="bildschirmfoto 2018-06-22 um 11 55 05" src="https://user-images.githubusercontent.com/36450093/41780489-1fb144d2-7635-11e8-8d08-d11fb8d8899e.png">

- [ ] Please add a sold sign here.
<img width="289" alt="bildschirmfoto 2018-06-22 um 11 55 25" src="https://user-images.githubusercontent.com/36450093/41780490-1fff3dd6-7635-11e8-975e-07827afba729.png">

- [ ] this seems pixelated

<img width="146" alt="bildschirmfoto 2018-06-22 um 11 53 21" src="https://user-images.githubusercontent.com/36450093/41781390-aa6edf7e-7637-11e8-96a4-7a40196c0a73.png">

- [ ] this is off
<img width="1380" alt="bildschirmfoto 2018-06-22 um 11 53 14" src="https://user-images.githubusercontent.com/36450093/41781376-a49e5cd2-7637-11e8-9a57-3b2b99de4a14.png">

**Comment by 128-95** [comment]
The name of the legendary cat will not be changed at this point. We can change the description however.
